### ISSUE TITLE
sequencer-relayer: use cometbft websocket

### ISSUE THREAD

**Issue by joroshiba** [astriaorg/astria#279] opened 2023-08-17 16:59 UTC
Right now sequencer relayer runs on a polling tick to grab new blocks from the cometbft instance. This requires we poll the sequencer client, which introduces complexity to tests, and doesn't guarantee we get new blocks ASAP.

We can update this to use a [websocket connection subscription](https://docs.cometbft.com/v0.37/core/subscription) for cometbft, and instead have a subscription push event to the relayer.

**Comment by noot** [comment] 2023-09-19 18:51
duplicate of #333

**Closed** 2024-03-25 15:46 UTC
Labels: sequencer-relayer, refactor, tech-debt
