### ISSUE TITLE
Ensure that conductor can deal with sequencer blocks that are received out of order

### ISSUE THREAD

**Issue by SuperFluffy** [astriaorg/astria#183] opened 2023-07-19 14:14 UTC
I believe that right now submitting out of order does not work. 

This should be logic we have in conductor, but could break functionality until then.

_Originally posted by @joroshiba in https://github.com/astriaorg/astria/pull/150#discussion_r1267621067_

**Comment by joroshiba** [comment] 2023-07-31 22:38
Duplicate of #15

**Closed by joroshiba** 2023-07-31 22:38 UTC
Labels: conductor
