### ISSUE TITLE
conductor: reevaluate block queue parent/executed block relations after new v1alpha2 api is implemented

### ISSUE THREAD

**Issue by sambukowski** [astriaorg/astria#220] opened 2023-08-04 18:21 UTC
investigate how the block queue looks at block relationships once #205 has been implemented
specifically look at `Executor::last_executed_seq_block_hash`

**Comment by sambukowski** [comment] 2023-08-21 18:59
the current implementation of the block queue in #284 does keep this in mind. so the refactor here is likely to be limited.

**Comment by joroshiba** [comment] 2023-09-07 18:32
Duplicate of #285 + #230

**Closed by joroshiba** 2023-09-07 18:32 UTC
Labels: conductor
