### ISSUE TITLE
conductor: ensure that DA and sequencer blocks are not executed out of order

### ISSUE THREAD

**Issue by SuperFluffy** [astriaorg/astria#464] opened 2023-10-05 19:37 UTC
I believe we have a problematic race condition bug here in 2 different instances:

1. If blocks are received out of order from DA, they will be executed out of order potentially.
2. On startup, if there are blocks being synced (in sequencer_reader loop), and this fires off some new data, again executing out of order.

The first one we can call a bug and hope doesn't happen, create an issue around the second I believe is pretty problematic.

_Originally posted by @joroshiba in https://github.com/astriaorg/astria/pull/455#discussion_r1344808459_

**Comment by noot** [comment] 2023-10-06 18:10
duplicate of #323?

**Comment by noot** [comment] 2024-03-18 21:04
closing as completed

**Closed by noot** 2024-03-18 21:04 UTC
Labels: conductor
