### ISSUE TITLE
refactor kubernetes testing setup to a common crate

### ISSUE THREAD

**Issue by SuperFluffy** [astriaorg/astria#26] opened 2023-05-19 15:36 UTC
`astria-conductor-test` and `astria-sequencer-relayer-test` share a lot of common code to setup kubernetes environments to run their tests. This needs to be refactored into a common crate.

**Comment by noot** [comment] 2023-07-13 21:10
duplicate of #143

**Closed by noot** 2023-07-13 21:10 UTC
Labels: refactor
